import { DEFAULT_WORKFLOW_PACK_KEY, isWorkflowPackKey, type WorkflowPackKey } from "./definitions.ts";

type SupportedLang = "ko" | "en" | "ja" | "zh";

function normalizeLang(raw: string | null | undefined): SupportedLang {
  const value = String(raw ?? "")
    .trim()
    .toLowerCase();
  if (value.startsWith("ko")) return "ko";
  if (value.startsWith("ja")) return "ja";
  if (value.startsWith("zh")) return "zh";
  return "en";
}

function normalizePackKey(raw: string | null | undefined): WorkflowPackKey {
  if (isWorkflowPackKey(raw)) return raw;
  return DEFAULT_WORKFLOW_PACK_KEY;
}

export function buildWorkflowPackExecutionGuidance(
  packKeyRaw: string | null | undefined,
  langRaw: string | null | undefined,
  options?: {
    videoArtifactRelativePath?: string | null;
  },
): string {
  const packKey = normalizePackKey(packKeyRaw);
  if (packKey !== "video_preprod") return "";

  const lang = normalizeLang(langRaw);
  const artifactPath = String(options?.videoArtifactRelativePath ?? "").trim() || "video_output/final.mp4";
  const ruleLines: Record<SupportedLang, string[]> = {
    ko: [
      "[Video Output Requirement]",
      "- 이 작업은 문서만 생성하면 완료가 아닙니다. 실제 영상 파일을 생성해야 합니다.",
      "- 순서 고정: 문서화/기획/회의 반영 작업을 모두 끝낸 뒤 마지막 단계에서 렌더링하세요.",
      "- 리뷰 보완 라운드에서 다시 실행할 때는 보완 내용을 반영한 뒤 같은 출력 파일로 재렌더링하세요.",
      `- 최종 산출물은 반드시 \`${artifactPath}\` 경로에 저장하세요. (프로젝트명_부서명_final.mp4 규칙)`,
      "- 다른 태스크의 결과를 덮어쓰지 않도록 `final.mp4` 단일 파일만 고집하지 마세요.",
      "- 렌더링 엔진은 반드시 Remotion을 사용하세요. ffmpeg 단독 슬라이드 합성이나 다른 영상 생성기로 대체하지 마세요.",
      "- Python(moviepy/Pillow) 기반 렌더링은 금지합니다.",
      '- Remotion 패키지 버전은 반드시 4.0.429 이상을 사용하세요. package.json에 `"remotion": "^4.0.429"`, `"@remotion/cli": "^4.0.429"`, `"@remotion/transitions": "^4.0.429"`, `"@remotion/google-fonts": "^4.0.429"` 등 @remotion/* 패키지를 동일 버전으로 통일하세요.',
      "- 우선 Remotion 런타임을 준비하세요: `pnpm exec remotion browser ensure`",
      "- `remotion-dev/skills#remotion-best-practices` 스킬이 없으면 시스템이 자동 설치 후 문서고 학습 이력으로 기록합니다.",
      "- 위 명령이 실패하면 fallback으로 실행하세요: `pnpm --package=@remotion/cli dlx remotion browser ensure`",
      "- Remotion 엔트리(`index.ts`, `Root.tsx`, `Composition.tsx`)를 프로젝트 내에 만들고, 아래 형태로 렌더를 실행하세요:",
      `  \`pnpm exec remotion render <entry-file> <composition-id> ${artifactPath} --log=verbose\``,
      `- 렌더 후 \`${artifactPath}\` 파일 존재 여부와 파일 크기(\`ls -lh ${artifactPath}\`)를 확인해 보고에 포함하세요.`,
      "",
      "[Video Quality Requirements]",
      "- 해상도: 1920×1080 (Full HD) 이상, fps: 30",
      "- Composition 설정: <Composition width={1920} height={1080} fps={30} />",
      "- 애니메이션: CSS transition/animation 사용 금지 — 반드시 useCurrentFrame() + interpolate()/spring() 사용",
      "- spring 기본 설정: { damping: 200 } (자연스러운 모션, 바운스 없음)",
      "- 장면 전환: @remotion/transitions의 TransitionSeries 사용 (fade, slide, wipe 등)",
      "  - 전환 시간: linearTiming({ durationInFrames: 15 }) 이상",
      "- 텍스트 애니메이션: spring() 기반 staggered 입장 효과 사용",
      "- 색상: 프로젝트 브랜드 컬러 활용, 그라데이션/그림자로 깊이감",
      "- 타이포그래피: @remotion/google-fonts로 웹폰트 로드",
      "- Sequence마다 premountFor={1 * fps} 설정 (프리로딩)",
      "",
      "[High Quality Direction]",
      "- 기본 길이는 55~65초로 맞추고, 장면별 목적(후킹/핵심 기능/신뢰 요소/마무리 CTA)을 명시하세요.",
      "- 정적인 슬라이드 나열 금지: 8~12개 이상 샷으로 구성하고, 한 샷이 3초 이상 정지되지 않게 구성하세요.",
      "- 컷마다 카메라/레이아웃/텍스트 모션을 분리 설계해 템플릿 느낌을 피하고 리듬을 만드세요.",
      "- 시작 2~4초 구간에 마스코트/브랜드 캐릭터 이미지가 있으면 인트로 키비주얼로 활용하세요.",
      "- 자막/텍스트는 safe area(좌우 8%, 상하 10%) 안에 배치하고, 대비비율과 가독성(최소 2단 계층)을 보장하세요.",
      "- 화면 텍스트 정제: `\\n`, `\\t`, 백틱, 마크다운 기호(`#`, `*`, `-`) 같은 원문 태그를 그대로 노출하지 마세요.",
      "- 줄바꿈이 필요하면 이스케이프 문자열이 아닌 실제 줄바꿈/레이아웃 분리로 처리하세요.",
      "- 최종 리포트에 씬 타임라인(초 단위) + 품질 체크리스트 결과를 함께 남기세요.",
    ],
    en: [
      "[Video Output Requirement]",
      "- This task is NOT complete with planning docs only. You must produce a real video file.",
      "- Fixed order: finish documentation/planning/meeting updates first, then render in the final step.",
      "- On review-remediation reruns, apply fixes first and re-render to the same output path.",
      `- Save the final artifact at \`${artifactPath}\`. (project_department_final.mp4 pattern)`,
      "- Do not force a single `final.mp4` filename when it can overwrite other tasks.",
      "- Rendering engine is fixed to Remotion. Do not replace it with ffmpeg-only slide stitching or other generators.",
      "- Python renderers (moviepy/Pillow) are prohibited.",
      '- Remotion packages MUST use version 4.0.429 or above. In package.json, use `"remotion": "^4.0.429"`, `"@remotion/cli": "^4.0.429"`, `"@remotion/transitions": "^4.0.429"`, `"@remotion/google-fonts": "^4.0.429"`, etc. All @remotion/* packages must share the same version.',
      "- Prepare the Remotion runtime first: `pnpm exec remotion browser ensure`",
      "- If `remotion-dev/skills#remotion-best-practices` is missing, the system auto-installs it and records it as learned.",
      "- If that fails, run fallback: `pnpm --package=@remotion/cli dlx remotion browser ensure`",
      "- Create a Remotion entry (`index.ts`, `Root.tsx`, `Composition.tsx`) in the project and render with:",
      `  \`pnpm exec remotion render <entry-file> <composition-id> ${artifactPath} --log=verbose\``,
      `- After rendering, verify file existence and size (\`ls -lh ${artifactPath}\`) and include it in your report.`,
      "",
      "[Video Quality Requirements]",
      "- Resolution: 1920×1080 (Full HD) minimum, fps: 30",
      "- Composition config: <Composition width={1920} height={1080} fps={30} />",
      "- Animation: NEVER use CSS transition/animation — always use useCurrentFrame() + interpolate()/spring()",
      "- spring defaults: { damping: 200 } (smooth motion, no bounce)",
      "- Scene transitions: use TransitionSeries from @remotion/transitions (fade, slide, wipe, etc.)",
      "  - Transition timing: linearTiming({ durationInFrames: 15 }) minimum",
      "- Text animation: use spring()-based staggered entrance effects",
      "- Colors: leverage project brand colors, add depth with gradients/shadows",
      "- Typography: load web fonts via @remotion/google-fonts",
      "- Add premountFor={1 * fps} on each Sequence for preloading",
      "",
      "[High Quality Direction]",
      "- Target 55-65 seconds by default and define scene goals (hook/core value/proof/CTA).",
      "- Avoid static slide-show output: use at least 8-12 shots and keep single-shot stillness under 3 seconds.",
      "- Design motion per shot (camera/layout/text) to avoid template-like pacing.",
      "- If a mascot/brand character image exists, use it as the opening key visual for the first 2-4 seconds.",
      "- Keep subtitles/text within safe area (8% horizontal, 10% vertical) with clear hierarchy and contrast.",
      "- On-screen text must be sanitized: never render raw escape sequences like `\\n`/`\\t`, backticks, or markdown tokens (`#`, `*`, `-`).",
      "- If a line break is needed, use real layout line breaks, not escaped string literals.",
      "- In the final report, include a second-by-second scene timeline and a quality checklist result.",
    ],
    ja: [
      "[Video Output Requirement]",
      "- このタスクは企画ドキュメントだけでは完了ではありません。実際の動画ファイルを生成してください。",
      "- 順序固定: 文書化/企画/会議反映をすべて完了した後、最後にレンダリングしてください。",
      "- レビュー補完ラウンドで再実行する場合は、補完反映後に同じ出力先へ再レンダリングしてください。",
      `- 最終成果物は必ず \`${artifactPath}\` に保存してください。（project_department_final.mp4 ルール）`,
      "- 他タスク成果物の上書きを避けるため、単一の `final.mp4` 固定運用は避けてください。",
      "- レンダリングエンジンは Remotion 固定です。ffmpeg単体のスライド結合や他生成器へ置換しないでください。",
      "- Python（moviepy/Pillow）系レンダリングは禁止です。",
      '- Remotion パッケージは必ずバージョン 4.0.429 以上を使用してください。package.json に `"remotion": "^4.0.429"`, `"@remotion/cli": "^4.0.429"`, `"@remotion/transitions": "^4.0.429"`, `"@remotion/google-fonts": "^4.0.429"` 等、@remotion/* を同一バージョンで統一してください。',
      "- まず Remotion ランタイムを準備: `pnpm exec remotion browser ensure`",
      "- `remotion-dev/skills#remotion-best-practices` が未導入の場合、システムが自動インストールし学習履歴へ記録します。",
      "- 失敗した場合はフォールバック: `pnpm --package=@remotion/cli dlx remotion browser ensure`",
      "- プロジェクト内に Remotion エントリ（`index.ts`, `Root.tsx`, `Composition.tsx`）を作成し、次でレンダリングしてください:",
      `  \`pnpm exec remotion render <entry-file> <composition-id> ${artifactPath} --log=verbose\``,
      `- レンダリング後、\`${artifactPath}\` の存在とサイズ（\`ls -lh ${artifactPath}\`）を確認し、報告に含めてください。`,
      "",
      "[Video Quality Requirements]",
      "- 解像度: 1920×1080 (Full HD) 以上、fps: 30",
      "- Composition 設定: <Composition width={1920} height={1080} fps={30} />",
      "- アニメーション: CSS transition/animation 使用禁止 — 必ず useCurrentFrame() + interpolate()/spring() を使用",
      "- spring デフォルト: { damping: 200 }（スムーズモーション、バウンスなし）",
      "- シーン遷移: @remotion/transitions の TransitionSeries を使用（fade, slide, wipe 等）",
      "  - 遷移時間: linearTiming({ durationInFrames: 15 }) 以上",
      "- テキストアニメーション: spring() ベースのスタガード入場効果を使用",
      "- カラー: プロジェクトブランドカラーを活用、グラデーション/シャドウで奥行き感",
      "- タイポグラフィ: @remotion/google-fonts でウェブフォントをロード",
      "- 各 Sequence に premountFor={1 * fps} を設定（プリロード）",
      "",
      "[High Quality Direction]",
      "- 基本尺は55〜65秒を目安にし、各シーンの目的（フック/価値/信頼/CTA）を明確化してください。",
      "- 静的スライドの羅列は禁止。8〜12ショット以上で構成し、1ショットの静止を3秒未満に抑えてください。",
      "- カメラ/レイアウト/テキストのモーションをショット単位で設計し、テンプレ感を避けてください。",
      "- マスコット/ブランド画像がある場合、冒頭2〜4秒のキービジュアルとして活用してください。",
      "- 字幕/テキストは safe area（左右8%、上下10%）内に配置し、可読性と階層を担保してください。",
      "- 画面テキストは正規化し、`\\n`/`\\t` やバッククォート、Markdown記号（`#`, `*`, `-`）をそのまま表示しないでください。",
      "- 改行が必要な場合はエスケープ文字列ではなく、実レイアウト上の改行で処理してください。",
      "- 最終レポートには秒単位のシーンタイムラインと品質チェック結果を含めてください。",
    ],
    zh: [
      "[Video Output Requirement]",
      "- 本任务仅产出策划文档不算完成，必须生成真实视频文件。",
      "- 固定顺序：先完成文档/策划/会议结论落实，再在最后一步渲染视频。",
      "- 评审整改轮次重新执行时，先完成整改，再渲染到同一路径。",
      `- 最终产物必须保存到 \`${artifactPath}\`。（project_department_final.mp4 规则）`,
      "- 不要固定只写 `final.mp4`，避免覆盖其他任务产物。",
      "- 渲染引擎固定为 Remotion，不要替换为仅 ffmpeg 拼接或其他视频生成器。",
      "- 禁止使用 Python（moviepy/Pillow）渲染方案。",
      '- Remotion 包版本必须使用 4.0.429 以上。在 package.json 中使用 `"remotion": "^4.0.429"`、`"@remotion/cli": "^4.0.429"`、`"@remotion/transitions": "^4.0.429"`、`"@remotion/google-fonts": "^4.0.429"` 等，所有 @remotion/* 包必须统一版本。',
      "- 先准备 Remotion 运行环境：`pnpm exec remotion browser ensure`",
      "- 若缺少 `remotion-dev/skills#remotion-best-practices`，系统会自动安装并记入文档库学习记录。",
      "- 若失败，执行回退命令：`pnpm --package=@remotion/cli dlx remotion browser ensure`",
      "- 在项目内创建 Remotion 入口（`index.ts`, `Root.tsx`, `Composition.tsx`），并执行渲染：",
      `  \`pnpm exec remotion render <entry-file> <composition-id> ${artifactPath} --log=verbose\``,
      `- 渲染完成后，检查 \`${artifactPath}\` 是否存在及文件大小（\`ls -lh ${artifactPath}\`），并写入报告。`,
      "",
      "[Video Quality Requirements]",
      "- 分辨率: 1920×1080 (Full HD) 以上, fps: 30",
      "- Composition 配置: <Composition width={1920} height={1080} fps={30} />",
      "- 动画: 禁止使用 CSS transition/animation — 必须使用 useCurrentFrame() + interpolate()/spring()",
      "- spring 默认: { damping: 200 }（平滑运动，无弹跳）",
      "- 场景转场: 使用 @remotion/transitions 的 TransitionSeries（fade, slide, wipe 等）",
      "  - 转场时间: linearTiming({ durationInFrames: 15 }) 以上",
      "- 文字动画: 使用 spring() 交错入场效果",
      "- 色彩: 运用项目品牌色，通过渐变/阴影增加层次感",
      "- 字体: 通过 @remotion/google-fonts 加载网络字体",
      "- 每个 Sequence 设置 premountFor={1 * fps}（预加载）",
      "",
      "[High Quality Direction]",
      "- 默认时长控制在 55-65 秒，并为每个场景定义目标（开场钩子/核心价值/可信背书/CTA）。",
      "- 禁止静态幻灯片堆叠：至少 8-12 个镜头，单镜头静止不超过 3 秒。",
      "- 按镜头拆分设计相机/版式/文字动效，避免模板感。",
      "- 若存在吉祥物/品牌角色图片，前 2-4 秒必须作为开场关键视觉使用。",
      "- 字幕与文字需放在 safe area（横向8%、纵向10%）内，并保证层级与对比度。",
      "- 屏幕文字必须做净化：禁止直接显示 `\\n`/`\\t`、反引号或 Markdown 符号（`#`, `*`, `-`）。",
      "- 需要换行时请使用真实布局换行，不要输出转义字符串字面量。",
      "- 最终报告需附带按秒场景时间线与质量检查结果。",
    ],
  };

  return ruleLines[lang].join("\n");
}
