export const ROUTE_RUNTIME_HELPER_KEYS = [
  "detectLang",
  "detectTargetDepartments",
  "findTeamLeader",
  "formatTaskSubtaskProgressSummary",
  "getDeptName",
  "getDeptRoleConstraint",
  "getPreferredLanguage",
  "getRoleLabel",
  "l",
  "pickL",
  "prettyStreamJson",
  "processSubtaskDelegations",
  "recoverCrossDeptQueueAfterMissingCallback",
  "refreshCliUsageData",
  "scheduleNextReviewRound",
  "resolveLang",
  "resolveProjectPath",
  "sendAgentMessage",
  "reconcileCrossDeptSubtasks",
] as const;
